### PR TITLE
Fixed typos

### PR DESCRIPTION
**Pull request by pborreli**

### CODE REVIEW

**Comment by noisebleed** [comment]
@pborreli you just can't be that fast. Are you a bot or something?

**Comment by pborreli** [comment]
I'm not a bot, but thanks for the compliment :speedboat:

**Comment by dragoonis** [comment]
@pborreli we love typo bots! :+1:

**Comment by dragoonis** [comment]
more more!

**Comment by noisebleed** [comment]
bot != boat

**Comment by noisebleed** [comment]
that's a typo there

**Pull request merged**
