### PR TITLE
update php minimal version to 5.3.23

### PR DESCRIPTION
**Pull request by samsonasik**
as zend framework 2 2.3 required.

### CODE REVIEW

**Comment by samsonasik** [comment]
ping @dragoonis

**Comment by dragoonis** [comment]
@samsonasik thank you for your contribution! appreciated.

**Comment by dragoonis** [comment]
To chat on anything - you can find us on `irc.freenode.net #ppi` - or twitter is fine.

**Comment by samsonasik** [comment]
@dragoonis  you're welcome ;), noted ;)

**Pull request merged**
